apiVersion: v1
kind: Service
metadata:
  name: iot-playground-service
spec:
  selector:
    app: iot-playground
  ports:
  - name: iot-playground-port
    port: 4242
    targetPort: 8888
    protocol: TCP
  type:
    LoadBalancer
